name: build-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - meson
  - ninja
  - llvm
  - clang
  - boost-cpp
  - zlib
  - gtest
  - readline
  - pkg-config  # Helps with library discovery