#!/bin/bash

# Script to clean coverage files generated by LLVM instrumentation

set -e

echo "Cleaning LLVM coverage files..."

# Remove profraw files from root directory
if [ -f "default.profraw" ]; then
    echo "  Removing default.profraw from root directory"
    rm -f default.profraw
fi

# Remove profraw files from current directory
find . -maxdepth 1 -name "*.profraw" -type f -delete 2>/dev/null || true
find . -maxdepth 1 -name "*.profdata" -type f -delete 2>/dev/null || true

# Remove coverage directory if it exists
if [ -d "buildDir/coverage" ]; then
    echo "  Removing buildDir/coverage/"
    rm -rf buildDir/coverage
fi

echo "Coverage files cleaned successfully!"
