#!/usr/bin/env python3
"""Convert CSV node/edge files into a TypeScript file with Cypher CREATE statements.

Usage:
    python scripts/csv_to_cypher.py \
        --nodes /path/to/nodes.csv \
        --edges /path/to/edges.csv \
        --node-label Character \
        --edge-type INTERACTS_WITH \
        --output docs/apps/docs/home/data/got-seed.ts \
        --export-name GOT_SEED_QUERIES

Expected CSV formats:
    nodes: Id,Label[,Weight]
    edges: Source,Target[,Weight][,Type]
"""

import argparse
import csv
import sys
from pathlib import Path


def escape_cypher(s: str) -> str:
    """Escape single quotes and backslashes for Cypher string literals."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def read_nodes(path: str) -> list[dict]:
    """Read nodes CSV. Expected columns: Id, Label, optional Weight."""
    nodes = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            node = {
                "id": row.get("Id", "").strip(),
                "label": row.get("Label", row.get("Id", "")).strip(),
            }
            if "Weight" in row and row["Weight"].strip():
                try:
                    node["weight"] = int(row["Weight"])
                except ValueError:
                    try:
                        node["weight"] = float(row["Weight"])
                    except ValueError:
                        pass
            nodes.append(node)
    return nodes


def read_edges(path: str) -> list[dict]:
    """Read edges CSV. Expected columns: Source, Target, optional Weight, Type."""
    edges = []
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            edge = {
                "source": row.get("Source", "").strip(),
                "target": row.get("Target", "").strip(),
            }
            if "Weight" in row and row["Weight"].strip():
                try:
                    edge["weight"] = int(row["Weight"])
                except ValueError:
                    try:
                        edge["weight"] = float(row["Weight"])
                    except ValueError:
                        pass
            if "Type" in row and row["Type"].strip():
                edge["type"] = row["Type"].strip()
            edges.append(edge)
    return edges


def generate_node_queries(
    nodes: list[dict], node_label: str, batch_size: int = 20
) -> list[str]:
    """Generate batched CREATE statements for nodes."""
    queries = []
    for i in range(0, len(nodes), batch_size):
        batch = nodes[i : i + batch_size]
        creates = []
        for node in batch:
            esc_id = escape_cypher(node["id"])
            esc_label = escape_cypher(node["label"])
            props = f"id: '{esc_id}', name: '{esc_label}'"
            if "weight" in node:
                props += f", weight: {node['weight']}"
            creates.append(f"(:{node_label} {{{props}}})")
        query = "CREATE " + ", ".join(creates)
        queries.append(query)
    return queries


def generate_edge_queries(
    edges: list[dict], node_label: str, default_edge_type: str
) -> list[str]:
    """Generate MATCH + CREATE statements for edges."""
    queries = []
    for edge in edges:
        esc_src = escape_cypher(edge["source"])
        esc_tgt = escape_cypher(edge["target"])
        edge_type = edge.get("type", default_edge_type)
        props = ""
        if "weight" in edge:
            props = f" {{weight: {edge['weight']}}}"
        query = (
            f"MATCH (a:{node_label} {{id: '{esc_src}'}}), "
            f"(b:{node_label} {{id: '{esc_tgt}'}}) "
            f"CREATE (a)-[:{edge_type}{props}]->(b)"
        )
        queries.append(query)
    return queries


def write_typescript(
    queries: list[str], output_path: str, export_name: str
) -> None:
    """Write queries as a TypeScript export."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"// Auto-generated by scripts/csv_to_cypher.py\n")
        f.write(f"// Do not edit manually\n\n")
        f.write(f"export const {export_name}: string[] = [\n")
        for q in queries:
            escaped = q.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
            f.write(f"  `{escaped}`,\n")
        f.write("];\n")


def main():
    parser = argparse.ArgumentParser(
        description="Convert CSV node/edge data to TypeScript Cypher statements"
    )
    parser.add_argument("--nodes", required=True, help="Path to nodes CSV")
    parser.add_argument("--edges", required=True, help="Path to edges CSV")
    parser.add_argument(
        "--node-label", default="Node", help="Cypher node label (default: Node)"
    )
    parser.add_argument(
        "--edge-type",
        default="CONNECTED_TO",
        help="Default edge type (default: CONNECTED_TO)",
    )
    parser.add_argument("--output", required=True, help="Output TypeScript file path")
    parser.add_argument(
        "--export-name",
        default="SEED_QUERIES",
        help="TypeScript export name (default: SEED_QUERIES)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=20,
        help="Nodes per CREATE batch (default: 20)",
    )

    args = parser.parse_args()

    if not Path(args.nodes).exists():
        print(f"Error: nodes file not found: {args.nodes}", file=sys.stderr)
        sys.exit(1)
    if not Path(args.edges).exists():
        print(f"Error: edges file not found: {args.edges}", file=sys.stderr)
        sys.exit(1)

    nodes = read_nodes(args.nodes)
    edges = read_edges(args.edges)

    print(f"Read {len(nodes)} nodes and {len(edges)} edges")

    node_queries = generate_node_queries(nodes, args.node_label, args.batch_size)
    edge_queries = generate_edge_queries(edges, args.node_label, args.edge_type)
    all_queries = node_queries + edge_queries

    print(f"Generated {len(node_queries)} node batches + {len(edge_queries)} edge queries")

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    write_typescript(all_queries, args.output, args.export_name)
    print(f"Written to {args.output}")


if __name__ == "__main__":
    main()
