/**
 * @file test_IndexManager_CompositeAndRange.cpp
 * @brief Branch coverage tests for IndexManager — composite index API,
 *        property range queries, and statistics counters.
 **/

#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <filesystem>
#include <gtest/gtest.h>
#include <memory>

#include "graph/core/Database.hpp"
#include "graph/core/Node.hpp"
#include "graph/storage/FileStorage.hpp"
#include "graph/storage/data/DataManager.hpp"
#include "graph/storage/indexes/IndexManager.hpp"

namespace fs = std::filesystem;

using graph::PropertyValue;

class IndexManagerCompositeTest : public ::testing::Test {
protected:
	void SetUp() override {
		boost::uuids::uuid uuid = boost::uuids::random_generator()();
		testFilePath = fs::temp_directory_path() /
					   ("test_im_composite_" + to_string(uuid) + ".dat");

		database = std::make_unique<graph::Database>(testFilePath.string());
		database->open();

		fileStorage = database->getStorage();
		dataManager = fileStorage->getDataManager();
		indexManager = database->getQueryEngine()->getIndexManager();
	}

	void TearDown() override {
		if (database)
			database->close();
		database.reset();
		if (fs::exists(testFilePath))
			fs::remove(testFilePath);
	}

	fs::path testFilePath;
	std::unique_ptr<graph::Database> database;
	std::shared_ptr<graph::storage::FileStorage> fileStorage;
	std::shared_ptr<graph::storage::DataManager> dataManager;
	std::shared_ptr<graph::query::indexes::IndexManager> indexManager;
};

// ============================================================================
// Composite Index API (IndexManager lines 446-501)
// ============================================================================

TEST_F(IndexManagerCompositeTest, CreateCompositeIndex_WithName) {
	bool created = indexManager->createCompositeIndex(
		"idx_person_name_age", "node", "Person", {"name", "age"});
	EXPECT_TRUE(created);

	EXPECT_TRUE(indexManager->hasCompositeIndex("node", {"name", "age"}));
}

TEST_F(IndexManagerCompositeTest, CreateCompositeIndex_EmptyName_AutoGenerated) {
	// Cover line 452: name.empty() → auto-generate
	bool created = indexManager->createCompositeIndex(
		"", "node", "Person", {"name", "age"});
	EXPECT_TRUE(created);

	EXPECT_TRUE(indexManager->hasCompositeIndex("node", {"name", "age"}));
}

TEST_F(IndexManagerCompositeTest, CreateCompositeIndex_DuplicateName) {
	// Cover line 463: allIndexes.contains(name)
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"dup_comp", "node", "Person", {"name", "age"}));
	EXPECT_FALSE(indexManager->createCompositeIndex(
		"dup_comp", "node", "Person", {"x", "y"}));
}

TEST_F(IndexManagerCompositeTest, CreateCompositeIndex_EdgeType_Unsupported) {
	// Cover line 470: entityType == "edge" → return false
	bool created = indexManager->createCompositeIndex(
		"edge_comp", "edge", "KNOWS", {"since", "weight"});
	EXPECT_FALSE(created);
}

TEST_F(IndexManagerCompositeTest, HasCompositeIndex_EdgeType_ReturnsFalse) {
	// Cover line 490: entityType != "node" → return false
	EXPECT_FALSE(indexManager->hasCompositeIndex("edge", {"k1", "k2"}));
}

TEST_F(IndexManagerCompositeTest, HasCompositeIndex_NonExistent) {
	EXPECT_FALSE(indexManager->hasCompositeIndex("node", {"x", "y"}));
}

TEST_F(IndexManagerCompositeTest, FindNodeIdsByCompositeIndex_Basic) {
	// Create composite index
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_find", "node", "Person", {"name", "age"}));

	int64_t labelId = dataManager->getOrCreateLabelId("Person");

	// Create a node with both properties
	graph::Node n(0, labelId);
	n.addProperty("name", std::string("Alice"));
	n.addProperty("age", static_cast<int64_t>(30));
	dataManager->addNode(n);

	// The composite index should be updated via updateCompositeIndexForNode
	auto results = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Alice")), PropertyValue(static_cast<int64_t>(30))});
	EXPECT_GE(results.size(), 1UL);
}

TEST_F(IndexManagerCompositeTest, FindNodeIdsByCompositeIndex_NotFound) {
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_nf", "node", "X", {"a", "b"}));

	auto results = indexManager->findNodeIdsByCompositeIndex(
		{"a", "b"},
		{PropertyValue(std::string("nope")), PropertyValue(static_cast<int64_t>(0))});
	EXPECT_TRUE(results.empty());
}

TEST_F(IndexManagerCompositeTest, FindNodeIdsByCompositeIndex_NoIndex) {
	// No composite index exists at all → empty result
	auto results = indexManager->findNodeIdsByCompositeIndex(
		{"x", "y"},
		{PropertyValue(static_cast<int64_t>(1)), PropertyValue(static_cast<int64_t>(2))});
	EXPECT_TRUE(results.empty());
}

// ============================================================================
// updateCompositeIndexForNode / removeCompositeIndexForNode (lines 521-599)
// ============================================================================

TEST_F(IndexManagerCompositeTest, CompositeIndexUpdate_OnNodeUpdate) {
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_upd", "node", "Person", {"name", "age"}));

	int64_t labelId = dataManager->getOrCreateLabelId("Person");

	// Add node with both composite properties
	graph::Node n1(0, labelId);
	n1.addProperty("name", std::string("Bob"));
	n1.addProperty("age", static_cast<int64_t>(25));
	dataManager->addNode(n1);

	// Verify inserted into composite index
	auto res1 = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Bob")), PropertyValue(static_cast<int64_t>(25))});
	EXPECT_GE(res1.size(), 1UL);

	// Update the node (triggers removeCompositeIndexForNode + updateCompositeIndexForNode)
	graph::Node n2(n1.getId(), labelId);
	n2.addProperty("name", std::string("Bob"));
	n2.addProperty("age", static_cast<int64_t>(26));
	indexManager->onNodeUpdated(n1, n2);

	// Old composite entry should be gone
	auto resOld = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Bob")), PropertyValue(static_cast<int64_t>(25))});
	EXPECT_TRUE(resOld.empty());

	// New composite entry should exist
	auto resNew = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Bob")), PropertyValue(static_cast<int64_t>(26))});
	EXPECT_GE(resNew.size(), 1UL);
}

TEST_F(IndexManagerCompositeTest, CompositeIndex_NodeWithoutAllProperties_Skipped) {
	// Cover line 551: allPresent = false (node missing a required composite property)
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_skip", "node", "Person", {"name", "age"}));

	int64_t labelId = dataManager->getOrCreateLabelId("Person");

	// Node with only one of the two required properties
	graph::Node n(0, labelId);
	n.addProperty("name", std::string("Carol"));
	// Missing "age"
	dataManager->addNode(n);

	auto results = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Carol")), PropertyValue(static_cast<int64_t>(0))});
	EXPECT_TRUE(results.empty());
}

TEST_F(IndexManagerCompositeTest, CompositeIndex_NodeWithEmptyProperties_Skipped) {
	// Cover line 526: props.empty() → return in updateCompositeIndexForNode
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_empty", "node", "X", {"a", "b"}));

	int64_t labelId = dataManager->getOrCreateLabelId("X");
	graph::Node n(0, labelId);
	// No properties at all
	dataManager->addNode(n);

	SUCCEED(); // Just verify no crash
}

TEST_F(IndexManagerCompositeTest, CompositeIndex_NodeDeleted) {
	// Cover removeCompositeIndexForNode via onNodeDeleted
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_del", "node", "Person", {"name", "age"}));

	int64_t labelId = dataManager->getOrCreateLabelId("Person");

	graph::Node n(0, labelId);
	n.addProperty("name", std::string("Dave"));
	n.addProperty("age", static_cast<int64_t>(40));
	dataManager->addNode(n);

	auto res1 = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Dave")), PropertyValue(static_cast<int64_t>(40))});
	EXPECT_GE(res1.size(), 1UL);

	// Delete node
	graph::Node toDelete = dataManager->getNode(n.getId());
	auto props = dataManager->getNodeProperties(n.getId());
	toDelete.setProperties(props);
	dataManager->deleteNode(toDelete);

	auto res2 = indexManager->findNodeIdsByCompositeIndex(
		{"name", "age"},
		{PropertyValue(std::string("Dave")), PropertyValue(static_cast<int64_t>(40))});
	EXPECT_TRUE(res2.empty());
}

TEST_F(IndexManagerCompositeTest, CompositeIndex_NullPropertyValue_Skipped) {
	// Cover line 551: it->second.getType() == PropertyType::NULL_TYPE
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_null", "node", "X", {"a", "b"}));

	int64_t labelId = dataManager->getOrCreateLabelId("X");
	graph::Node n(100, labelId);
	n.addProperty("a", std::string("val"));
	n.addProperty("b", std::monostate{}); // NULL property
	indexManager->onNodeAdded(n);

	auto results = indexManager->findNodeIdsByCompositeIndex(
		{"a", "b"},
		{PropertyValue(std::string("val")), PropertyValue(std::monostate{})});
	EXPECT_TRUE(results.empty());
}

// ============================================================================
// findNodeIdsByPropertyRange (lines 434-442)
// ============================================================================

TEST_F(IndexManagerCompositeTest, FindNodeIdsByPropertyRange_Basic) {
	(void)indexManager->createIndex("idx_level", "node", "Player", "level");

	int64_t labelId = dataManager->getOrCreateLabelId("Player");

	for (int i = 1; i <= 5; ++i) {
		graph::Node n(0, labelId);
		dataManager->addNode(n);
		dataManager->addNodeProperties(n.getId(), {{"level", static_cast<int64_t>(i * 10)}});
	}

	auto results = indexManager->findNodeIdsByPropertyRange(
		"level", PropertyValue(static_cast<int64_t>(20)), PropertyValue(static_cast<int64_t>(40)));
	EXPECT_GE(results.size(), 2UL); // 20, 30, 40
}

TEST_F(IndexManagerCompositeTest, FindNodeIdsByPropertyRange_EmptyResult) {
	(void)indexManager->createIndex("idx_score", "node", "G", "score");

	auto results = indexManager->findNodeIdsByPropertyRange(
		"score", PropertyValue(static_cast<int64_t>(100)), PropertyValue(static_cast<int64_t>(200)));
	EXPECT_TRUE(results.empty());
}

// ============================================================================
// Statistics counters (lookups, indexHits, resetStats)
// ============================================================================

TEST_F(IndexManagerCompositeTest, StatsCounters) {
	(void)indexManager->createIndex("idx_stats", "node", "S", "val");

	indexManager->resetStats();
	EXPECT_EQ(indexManager->lookups(), 0u);
	EXPECT_EQ(indexManager->indexHits(), 0u);

	// A lookup with no data → hit count stays 0
	(void)indexManager->findNodeIdsByProperty("val", static_cast<int64_t>(1));
	EXPECT_EQ(indexManager->lookups(), 1u);
	EXPECT_EQ(indexManager->indexHits(), 0u);

	// Add data and find → hit count increases
	int64_t labelId = dataManager->getOrCreateLabelId("S");
	graph::Node n(0, labelId);
	dataManager->addNode(n);
	dataManager->addNodeProperties(n.getId(), {{"val", static_cast<int64_t>(42)}});

	(void)indexManager->findNodeIdsByProperty("val", static_cast<int64_t>(42));
	EXPECT_EQ(indexManager->lookups(), 2u);
	EXPECT_EQ(indexManager->indexHits(), 1u);

	indexManager->resetStats();
	EXPECT_EQ(indexManager->lookups(), 0u);
	EXPECT_EQ(indexManager->indexHits(), 0u);
}

TEST_F(IndexManagerCompositeTest, StatsCounters_Label) {
	(void)indexManager->createIndex("idx_lbl_stats", "node", "", "");

	indexManager->resetStats();

	int64_t labelId = dataManager->getOrCreateLabelId("StatNode");
	graph::Node n(0, labelId);
	dataManager->addNode(n);

	(void)indexManager->findNodeIdsByLabel("StatNode");
	EXPECT_EQ(indexManager->lookups(), 1u);
	EXPECT_GE(indexManager->indexHits(), 1u);
}

TEST_F(IndexManagerCompositeTest, StatsCounters_EdgeLabel) {
	(void)indexManager->createIndex("idx_elbl_stats", "edge", "", "");
	indexManager->resetStats();

	graph::Node n1(0, 0);
	graph::Node n2(0, 0);
	dataManager->addNode(n1);
	dataManager->addNode(n2);

	int64_t eLbl = dataManager->getOrCreateLabelId("STAT_REL");
	graph::Edge e(0, n1.getId(), n2.getId(), eLbl);
	dataManager->addEdge(e);

	(void)indexManager->findEdgeIdsByLabel("STAT_REL");
	EXPECT_EQ(indexManager->lookups(), 1u);
}

TEST_F(IndexManagerCompositeTest, StatsCounters_CompositeIndex) {
	EXPECT_TRUE(indexManager->createCompositeIndex(
		"comp_stats", "node", "X", {"a", "b"}));
	indexManager->resetStats();

	(void)indexManager->findNodeIdsByCompositeIndex(
		{"a", "b"},
		{PropertyValue(static_cast<int64_t>(1)), PropertyValue(static_cast<int64_t>(2))});
	EXPECT_EQ(indexManager->lookups(), 1u);
}

TEST_F(IndexManagerCompositeTest, StatsCounters_EdgeProperty) {
	(void)indexManager->createIndex("idx_ep_stats", "edge", "R", "weight");
	indexManager->resetStats();

	(void)indexManager->findEdgeIdsByProperty("weight", static_cast<int64_t>(10));
	EXPECT_EQ(indexManager->lookups(), 1u);
}

TEST_F(IndexManagerCompositeTest, StatsCounters_PropertyRange) {
	(void)indexManager->createIndex("idx_rng_stats", "node", "N", "score");
	indexManager->resetStats();

	(void)indexManager->findNodeIdsByPropertyRange(
		"score", PropertyValue(static_cast<int64_t>(0)), PropertyValue(static_cast<int64_t>(100)));
	EXPECT_EQ(indexManager->lookups(), 1u);
}
