include(FindPkgConfig)

function(zyx_add_pkg_config_interface target module_name)
    if(NOT PkgConfig_FOUND)
        find_package(PkgConfig QUIET)
    endif()
    if(NOT PkgConfig_FOUND)
        return()
    endif()

    string(MAKE_C_IDENTIFIER "${module_name}" module_id)
    string(TOUPPER "${module_id}" module_var)
    pkg_check_modules(${module_var} QUIET IMPORTED_TARGET ${module_name})
    if(${module_var}_FOUND)
        add_library(${target} INTERFACE IMPORTED GLOBAL)
        target_link_libraries(${target} INTERFACE PkgConfig::${module_var})
    endif()
endfunction()

function(zyx_require_target target message)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "${message}")
    endif()
endfunction()

function(zyx_find_common_dependencies)
    if(ZYX_WASM)
        zyx_find_wasm_dependencies()
        return()
    endif()

    find_package(ZLIB QUIET)
    if(TARGET ZLIB::ZLIB)
        add_library(zyx::zlib ALIAS ZLIB::ZLIB)
    else()
        zyx_add_pkg_config_interface(zyx_zlib_pkg zlib)
        if(TARGET zyx_zlib_pkg)
            add_library(zyx::zlib ALIAS zyx_zlib_pkg)
        endif()
    endif()
    zyx_require_target(zyx::zlib "ZLIB was not found. Run Conan install or install zlib development files.")

    if(ZYX_BUILD_APPS OR ZYX_BUILD_TESTS)
        find_package(Boost QUIET CONFIG COMPONENTS filesystem)
        if(TARGET Boost::filesystem)
            add_library(zyx_boost INTERFACE)
            target_link_libraries(zyx_boost INTERFACE Boost::filesystem)
            add_library(zyx::boost ALIAS zyx_boost)
        else()
            zyx_add_pkg_config_interface(zyx_boost_pkg boost)
            if(TARGET zyx_boost_pkg)
                add_library(zyx::boost ALIAS zyx_boost_pkg)
            endif()
        endif()
        zyx_require_target(zyx::boost "Boost filesystem/system was not found. Run Conan install or install Boost development files.")
    else()
        add_library(zyx_boost_stub INTERFACE)
        add_library(zyx::boost ALIAS zyx_boost_stub)
    endif()

    if(ZYX_BUILD_APPS)
        find_package(CLI11 QUIET CONFIG)
        if(TARGET CLI11::CLI11)
            add_library(zyx::cli11 ALIAS CLI11::CLI11)
        else()
            zyx_add_pkg_config_interface(zyx_cli11_pkg CLI11)
            if(TARGET zyx_cli11_pkg)
                add_library(zyx::cli11 ALIAS zyx_cli11_pkg)
            endif()
        endif()
        zyx_require_target(zyx::cli11 "CLI11 was not found. Run Conan install or install CLI11 development files.")
    else()
        add_library(zyx_cli11_stub INTERFACE)
        add_library(zyx::cli11 ALIAS zyx_cli11_stub)
    endif()

    find_package(antlr4-cppruntime QUIET CONFIG)
    if(TARGET antlr4_static)
        add_library(zyx::antlr4 ALIAS antlr4_static)
    elseif(TARGET antlr4_shared)
        add_library(zyx::antlr4 ALIAS antlr4_shared)
    elseif(TARGET antlr4-cppruntime::antlr4-cppruntime)
        add_library(zyx::antlr4 ALIAS antlr4-cppruntime::antlr4-cppruntime)
    else()
        find_package(antlr4-runtime QUIET CONFIG)
        if(TARGET antlr4_static)
            add_library(zyx::antlr4 ALIAS antlr4_static)
        elseif(TARGET antlr4_shared)
            add_library(zyx::antlr4 ALIAS antlr4_shared)
        else()
            zyx_add_pkg_config_interface(zyx_antlr4_pkg antlr4-cppruntime)
            if(TARGET zyx_antlr4_pkg)
                add_library(zyx::antlr4 ALIAS zyx_antlr4_pkg)
            endif()
        endif()
    endif()
    zyx_require_target(zyx::antlr4 "ANTLR4 C++ runtime was not found. Run Conan install with --build=\"antlr4-cppruntime/*\" or install antlr4-runtime.")
endfunction()

function(zyx_find_wasm_dependencies)
    if(NOT DEFINED ENV{ZYX_ANTLR4_WASM_DIR})
        set(ZYX_ANTLR4_WASM_DIR "${PROJECT_SOURCE_DIR}/emsdk/antlr4-wasm" CACHE PATH "ANTLR4 WASM install directory")
    else()
        set(ZYX_ANTLR4_WASM_DIR "$ENV{ZYX_ANTLR4_WASM_DIR}" CACHE PATH "ANTLR4 WASM install directory")
    endif()

    if(NOT EXISTS "${ZYX_ANTLR4_WASM_DIR}/lib/libantlr4-runtime.a")
        message(FATAL_ERROR "ANTLR4 WASM runtime not found at ${ZYX_ANTLR4_WASM_DIR}. Run ./scripts/setup_emsdk.sh first.")
    endif()

    add_library(zyx_antlr4_wasm STATIC IMPORTED GLOBAL)
    set_target_properties(zyx_antlr4_wasm PROPERTIES
        IMPORTED_LOCATION "${ZYX_ANTLR4_WASM_DIR}/lib/libantlr4-runtime.a"
        INTERFACE_INCLUDE_DIRECTORIES "${ZYX_ANTLR4_WASM_DIR}/include;${ZYX_ANTLR4_WASM_DIR}/include/antlr4-runtime"
    )
    add_library(zyx::antlr4 ALIAS zyx_antlr4_wasm)

    add_library(zyx_zlib_wasm INTERFACE)
    target_compile_options(zyx_zlib_wasm INTERFACE -sUSE_ZLIB=1)
    target_link_options(zyx_zlib_wasm INTERFACE -sUSE_ZLIB=1)
    add_library(zyx::zlib ALIAS zyx_zlib_wasm)

    add_library(zyx_boost_stub INTERFACE)
    add_library(zyx::boost ALIAS zyx_boost_stub)

    add_library(zyx_cli11_stub INTERFACE)
    add_library(zyx::cli11 ALIAS zyx_cli11_stub)
endfunction()

function(zyx_find_test_dependencies)
    find_package(GTest QUIET CONFIG)
    if(TARGET GTest::gtest)
        add_library(zyx::gtest ALIAS GTest::gtest)
    else()
        zyx_add_pkg_config_interface(zyx_gtest_pkg gtest)
        if(TARGET zyx_gtest_pkg)
            add_library(zyx::gtest ALIAS zyx_gtest_pkg)
        endif()
    endif()
    zyx_require_target(zyx::gtest "GoogleTest was not found. Run Conan install with tests enabled or install GTest.")

    if(TARGET GTest::gmock)
        add_library(zyx::gmock ALIAS GTest::gmock)
    else()
        zyx_add_pkg_config_interface(zyx_gmock_pkg gmock)
        if(TARGET zyx_gmock_pkg)
            add_library(zyx::gmock ALIAS zyx_gmock_pkg)
        else()
            add_library(zyx_gmock_fallback INTERFACE)
            target_link_libraries(zyx_gmock_fallback INTERFACE zyx::gtest)
            add_library(zyx::gmock ALIAS zyx_gmock_fallback)
        endif()
    endif()
endfunction()

zyx_find_common_dependencies()
