name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            native_file: compiler_options.ini
            llvm_cov: llvm-cov-20
            llvm_profdata: llvm-profdata-20

          - os: windows-latest
            native_file: compiler_options_win64.ini
            llvm_cov: llvm-cov
            llvm_profdata: llvm-profdata

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Tools
        run: pip install conan meson ninja

      - name: Install Pkg-Config (Windows)
        if: runner.os == 'Windows'
        run: choco install pkgconfiglite --allow-empty-checksums
        shell: cmd

      # -----------------------------------------------------------
      # Install LLVM/Clang
      # -----------------------------------------------------------

      - name: Install LLVM (Windows)
        if: runner.os == 'Windows'
        run: choco install llvm --version=20.1.4 --force
        shell: cmd

      - name: Install LLVM (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -sc)/ llvm-toolchain-$(lsb_release -sc)-20 main"
          sudo apt update
          sudo apt install -y clang-20 llvm-20 libc++-20-dev libc++abi-20-dev

      # -----------------------------------------------------------
      # Install Dependencies (Conan)
      # -----------------------------------------------------------
      - name: Install Dependencies with Conan
        run: |
          conan profile detect
          mkdir -p buildDir
          conan install . --output-folder=buildDir --build=missing

      # -----------------------------------------------------------
      # Build Phase (Windows)
      # -----------------------------------------------------------
      - name: Configure and Build (Windows)
        if: runner.os == 'Windows'
        run: |
          cd buildDir
          $FLAGS="-fprofile-instr-generate -fcoverage-mapping"
          
          # Native files: Conan generated + User override
          meson setup . .. --native-file conan_meson_native.ini --native-file ../${{ matrix.native_file }} -Dcpp_args="$FLAGS" -Dcpp_link_args="$FLAGS"
          meson compile
        shell: pwsh

      # -----------------------------------------------------------
      # Build Phase (Linux)
      # -----------------------------------------------------------
      - name: Configure and Build (Linux)
        if: runner.os == 'Linux'
        run: |
          cd buildDir
          export FLAGS="-fprofile-instr-generate -fcoverage-mapping"
          
          meson setup . .. --native-file conan_meson_native.ini --native-file ../${{ matrix.native_file }} -Dcpp_args="${FLAGS}" -Dcpp_link_args="${FLAGS}"
          meson compile

      # -----------------------------------------------------------
      # Test Phase
      # -----------------------------------------------------------
      - name: Run Unit Tests
        run: |
          cd buildDir
          export LLVM_PROFILE_FILE="$PWD/code-%p.profraw"
          meson test --verbose
        shell: bash

      # -----------------------------------------------------------
      # Report Generation Phase
      # -----------------------------------------------------------
      - name: Generate Coverage Report
        run: |
          python scripts/generate_coverage.py buildDir coverage.lcov "${{ matrix.llvm_cov }}" "${{ matrix.llvm_profdata }}"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true